### PR TITLE
Fix white on white text

### LINKED ISSUE #225: Maintenance page has white on white text
screen shot 2016-05-17 at 10 26 13 am

### PR DESCRIPTION
**Pull request by dmcinnes**
Fixes #225 and #227

This also fixes the design view of authorize client (http://localhost:5000/design/authorize when running locally)

Ready for review @heroku/api

### CODE REVIEW

File: lib/identity/design.rb [hunk 1]
```diff
@@ -72,5 +72,9 @@ class Design < Sinatra::Base
         slim :"design/index"
       end
     end
+
+    def client_deny_url
+      "https://id.heroku.com/#deny"
```
Comment (rwz) [inline lib/identity/design.rb]: How is that relevant to the white on white css bug?

Comment (dmcinnes) [inline lib/identity/design.rb]: I needed this fix to test the authorization endpoint in our design since the view calls this method.
https://github.com/heroku/identity/blob/master/lib/identity/design.rb#L51-L54

**Comment by rwz** [comment]
:+1:

**Comment by dmcinnes** [comment]
Thanks!
